### ISSUE TITLE
pgRoutingLayer realease 2.1 tasks

### ISSUE THREAD

**Issue by cvvergara** [cvvergara/pgrouting#28]
### Tasks before merging

- [x] Review issues and close the ones solved with this release
- [x] Link of closed issues with the release: https://github.com/pgRouting/pgRoutingLayer/issues?q=is%3Aissue+milestone%3A%22Release+2.1.0%22+is%3Aclosed

### Update master with latest develop

- [x] make pull request from github site
  - make sure its to master on pgRouting/pgRoutingLayer because it automatically points to Anita's repository

- [x] follow the instructions (because of conflicts)

```
git checkout develop
git merge master
git status
```
- [x] Fix the conflicts
From the last line the merging conflicts will show.

- [x] follow the instructions (because of conflicts)
```
git commit -a -m 'fixed merge conflicts'
git checkout master
git merge --no-ff develop
git push origin master
```

### Create the 2.1.0 tag

- [x] The current version 2.1 make the tag

```
git checkout master
git tag -a -m "Create the pgRoutingLayer-2.1.0 tag" pgRoutingLayer-2.1.0
git push --tags
```
- [x] make the release:
https://github.com/pgRouting/pgRoutingLayer/releases/tag/pgRoutingLayer-2.1.0
- [x] Put the link of the closed issues
- [x] Add some comments about changes

###  upload the zipped plugin code

A plugin is published when you upload the zipped plugin code to plugins.QGIS.org. This is usually done manually.
- [x] go to: https://github.com/pgRouting/pgRoutingLayer/releases/tag/pgRoutingLayer-2.1.0
   - [x] download the zip file
   - [x] extract file
   - [ ] rename extracted folder  to:  timemanager
   - [ ] create new zip file containing  timemanager folder
- goto: http://plugins.qgis.org/plugins/
 - [ ] click share plugin
 - [ ] Upload plugin
