### ISSUE TITLE
release 2.2.4

### ISSUE THREAD

**Issue by cvvergara** [cvvergara/pgrouting#38]
# Micro release is due to a critical bugs.

## 1. Information

Branch: master
```
git checkout master
git rev-parse HEAD
```
Commit: [0590656 ](https://github.com/pgRouting/pgrouting/tree/059065668526f6a8d094ab26c2ecc1c3b3237f5f )

### Double check fixes
Fixed on Master
- [x] #395
- [x] #543
- [x] #576
- [x] #591
- [x] #612
- [x] #653

Fixed on Develop
- [x] #395
- [ ] #543  need to checkout doc/src/installation/installation.rst into develop
- [x] #576
- [x] #591
- [x] #612
- [x] #653

### Tests

- [x]  [Travis](https://travis-ci.org/pgRouting/pgrouting/builds/148553424)
- [x]  [Jenkins](http://winnie.postgis.net:1500/view/pgRouting/job/pgRouting_matrix_master/170/ )

### task 2.1
**Modifications on the branch that fixes the issue**

- [x]  CMakeLists.txt [instructions](#issuecomment-238572917)
- [x]  utilities-any.result [instructions](#issuecomment-238574341)
- [x] VERSION [instructions](#issuecomment-238574517)
- [x] NEWS [instructions](#issuecomment-238575524)
- [x] 2_2_4.rst [instructions](#issuecomment-238576322)
- [x] changelog/index.rst [instructions](#issuecomment-238576521)
- [x] doc/index.rst [instructions](#issuecomment-238576720)
- [x] signatures [instructions](#issuecomment-238577029)
- [x] README.md [instructions](#issuecomment-238577312)

### task 2.2

- [x]  Run the tests [Instructions](#issuecomment-238619204)
- [x] Run the documentation queries [Instructions](#run-the-documentation-queries)

- [x] double check modified files:

```
git status
```
  - [x] add & commit modified files

```
git commit -a -m 'Preparing release 2.2.4'
git stash
```

Note The stash is necessary because of the pre-commit hook before changing branch

### task 2.3

  - [x] add the new signature into develop

```
git checkout develop
git pull

cp build/lib/pgrouting--2.2.4.sig tools/sigs/
git add tools/sigs/pgrouting--2.2.4.sig
```

- [x] the changelog

```
vi doc/src/changelog/release_notes.rst
```

  - [x] add the change log contents of 2.2.4
  - [x] add  to the "Table of contents"

```
   - :ref:`changelog_2_2_4`
```

- [x] Modify the change log on main page of documentation

```
vi doc/index.rst

```
find `change_log`
Insert where it belongs. 
```
   - :ref:`changelog_2_2_4`
```

- [x] commit changes in develop
```
git commit -a -m 'Adding 2.2.4 signatures'
git push
git stash
```
The stash is necessary because of the pre-commit hook

- [x] going back to working branch
```
git checkout master
git push

```

### Task 3.1

Information:
Branch: master
```
git checkout master
git rev-parse HEAD
```

Commit: [fd447cd](https://github.com/pgRouting/pgrouting/tree/fd447cd8901ca23fd6e13fef57dc81a63091eafe)

### Tests

- [x]  [Travis](https://travis-ci.org/pgRouting/pgrouting/builds/151032917)
- [x]  [Jenkins](http://winnie.postgis.net:1500/job/pgRouting_matrix_master/171/)

### Task 3.3

- [x] make sure .travis.yml only has *master* & *develop*

```
vi .travis.yml
```

- [x] Make sure VERSION has 2.2.4
```
vi VERSION

```

 

- [x] Compile with documentation [instructions] (#issuecomment-238601326)
- [x] Run documentation tests

```
tools/testers/algorithm-tester.pl

```

- [x] Run pgtap tests

```
dropdb  ___pgr___test___
createdb  ___pgr___test___
sh ./tools/testers/pg_prove_tests.sh vicky
dropdb  ___pgr___test___
```

- [x] Final commit

```
git commit -a -m 'Changes before tagging pgrouting-2.2.4'
git stash
git push

```

- [x] Build the final documentation

```
cd build
rm -rf doc
make doc
cd ..

```

- [x] Copy the documentation to the gh-pages
- [x] put the correct commit

```
git checkout gh-pages
git pull origin
rm -rf 2.2/*
cp -r build/doc/html/en 2.2
git status
git add 2.2/en/_sources/doc/src/changelog/2_2_4.txt
git add 2.2/en/doc/src/changelog/2_2_4.html 

#copy to latest documentation
rm -rf latest
cp -r 2.2 latest

git commit -a -m 'Updating to 2.2.4 documentation commit fd447cd'
git push
git checkout master

```

## THE TAG

- [x] create the tag & push it

```
git tag -a -m "Create the pgrouting-2.2.4 tag" pgrouting-2.2.4
git push --tags

```

- [x]  Edit the tag

https://github.com/pgRouting/pgrouting/releases/tag/pgrouting-2.2.4
- [x] verify the links on the sequence of commands
- [x] perform the sequence of commands
 
```

With the release of pgRouting 2.2.4 fixes compatibility errors with Fedora

 - To see the full list of changes check the list of `Git commits <https://github.com/pgRouting/pgrouting/commits>`_ on Github.
 - To see the issues closed by this release see the `Git closed issues <https://github.com/pgRouting/pgrouting/issues?q=is%3Aissue+milestone%3A%22Release+2.2.4%22+is%3Aclosed>`_ on Github.
 - For important changes see the following release notes.


Changes for release 2.2.4


- Bogus uses of extern "C"
- Build error on Fedora 24 + GCC 6.0
- Regression error pgr_nodeNetwork
```

**Comment by cvvergara** [comment]
### CMakeLists.txt

```
vi CMakeLists.txt

```
Change:
```
# PGROUTING version number.
set(PGROUTING_VERSION_MAJOR "2")
set(PGROUTING_VERSION_MINOR "2")
set(PGROUTING_VERSION_PATCH "2")
```
To
```
# PGROUTING version number.
set(PGROUTING_VERSION_MAJOR "2")
set(PGROUTING_VERSION_MINOR "2")
set(PGROUTING_VERSION_PATCH "3")
set(PGROUTING_GIT_TAG "pgrouting-2.2.3")
```
- [ ] Done

**Comment by cvvergara** [comment]
### utilities-any.result

```
vi doc/test/utilities-any.result

```

| Change | to
|--------|-----
| 2.2.3  | 2.2.4

- [ ] Done

**Comment by cvvergara** [comment]
### VERSION
```
vi VERSION

```

| Change | To
| --------- | --------
| pgrouting-2.2.3-< rest > branch | pgrouting-2.2.4-< rest > master

- [ ] Done

**Comment by cvvergara** [comment]
### NEWS

- [ ] fill this comment with the log change. (it is going to be used later)

```
vi NEWS
```

- [ ] Add on top of the file:
```
Changes for 2.2.4
-------------------------------------------------------------------------------

- FILL WITH CORRECT INFO
```

- [ ] Done

**Comment by cvvergara** [comment]
### 2_2_4.rst

- [ ] edit this comment use information from the NEWS

Create the log file for the release
```
vi doc/src/changelog/2_2_4.rst
```

Insert the following:
```
..
   ****************************************************************************
    pgRouting Manual
    Copyright(c) pgRouting Contributors

    This documentation is licensed under a Creative Commons Attribution-Share
    Alike 3.0 License: http://creativecommons.org/licenses/by-sa/3.0/
   ****************************************************************************

.. _changelog_2_2_4:

pgRouting 2.2.4 Release Notes
===============================================================================

With the release of pgRouting 2.2.4 fixes  FILL WITH CORRECT INFO

 - To see the full list of changes check the list of `Git commits <https://github.com/pgRouting/pgrouting/commits>`_ on Github.
 - To see the issues closed by this release see the `Git closed issues <https://github.com/pgRouting/pgrouting/issues?q=milestone%3ARelease-2.2.4+is%3Aclosed>`_ on Github.
 - For important changes see the following release notes.


Release Notes
-------------------------------------------------------------------------------


Changes for release 2.2.4

* FILL WITH CORRECT INFO
```

- [ ] Done

**Comment by cvvergara** [comment]
### changelog/index.rst

Modify the change log on Change log file
```
vi doc/src/changelog/index.rst

```

Insert on top of the list. 
```
   - :ref:`changelog_2_2_4`
```

Insert on top of the hidden tag
```
   2_2_4
```

- [ ] Done

**Comment by cvvergara** [comment]
### doc/index.rst

Modify the change log on main page of documentation
```
vi doc/index.rst
\change_log

```

Insert on top of the list. 
```
   - :ref:`changelog_2_2_4`
```

- [ ] Done

**Comment by cvvergara** [comment]
### Signatures
We are not allowing signature changes in micro releases, for upgrading to 2.2.4 create the signature file

```
cp tools/sigs/pgrouting--2.2.0.sig tools/sigs/pgrouting--2.2.4.sig
vi tools/sigs/pgrouting--2.2.4.sig

```
On the first line:

| Change | to
| ---- | -----
| #VERSION pgrouting 2.2.0 | #VERSION pgrouting 2.2.4

- [ ] done

**Comment by cvvergara** [comment]
### README.md

```
vi README.md

```
Change:
```
The *master* branch reflects the current 2.2.3 release.
```
to
```
The *master* branch reflects the current 2.2.4 release.
```

- [ ] Done

**Comment by cvvergara** [comment]
### Compile

```
cd build/
rm -rf *
cmake ..
make
sudo make install

```

**Comment by cvvergara** [comment]
### Compile with documentation

```
cd build/
rm -rf *
cmake -DWITH_DOC=ON ..
make
sudo make install
make doc
```

**Comment by cvvergara** [comment]
### Run the tests

- [ ] documentation tests
```
tools/testers/algorithm-tester.pl
createdb  ___pgr___test___
```

- [ ] pgtap tests
```
dropdb  ___pgr___test___
createdb  ___pgr___test___
sh ./tools/testers/pg_prove_tests.sh vicky
dropdb  ___pgr___test___
```

### updates from 2.2.x

- [ ] Update test from 2.2.0  to 2.2.4
```
createdb  ___test_update
psql  ___test_update  <<EOF
create extension postgis;
create extension pgrouting with version '2.2.0';
select pgr_version();
alter extension pgrouting update to '2.2.4';
select pgr_version();
EOF
dropdb   ___test_update
```
- [ ] Update test from 2.2.1  to 2.2.4
```
createdb  ___test_update
psql  ___test_update  <<EOF
create extension postgis;
create extension pgrouting with version '2.2.1';
select pgr_version();
alter extension pgrouting update to '2.2.4';
select pgr_version();
EOF
dropdb   ___test_update

```
- [ ] Update test from 2.2.2  to 2.2.4
```

createdb  ___test_update
psql  ___test_update  <<EOF
create extension postgis;
create extension pgrouting with version '2.2.2';
select pgr_version();
alter extension pgrouting update to '2.2.4';
select pgr_version();
EOF
dropdb   ___test_update

``` 
- [ ] Update test from 2.2.3  to 2.2.4
```

createdb  ___test_update
psql  ___test_update  <<EOF
create extension postgis;
create extension pgrouting with version '2.2.3';
select pgr_version();
alter extension pgrouting update to '2.2.4';
select pgr_version();
EOF
dropdb   ___test_update

``` 
### updates from 2.1.x

- [ ] Update test from 2.1.0  to 2.2.4
```
createdb  ___test_update
psql  ___test_update  <<EOF
create extension postgis;
create extension pgrouting with version '2.1.0';
select pgr_version();
alter extension pgrouting update to '2.2.4';
select pgr_version();
EOF
dropdb   ___test_update
```

### updates from 2.0.x

- [ ] Update test from 2.0.0  to 2.2.4
```
createdb  ___test_update
psql  ___test_update  <<EOF
create extension postgis;
create extension pgrouting with version '2.0.0';
select pgr_version();
alter extension pgrouting update to '2.2.4';
select pgr_version();
EOF
dropdb   ___test_update
```

- [ ] Update test from 2.0.1  to 2.2.4
```
createdb  ___test_update
psql  ___test_update  <<EOF
create extension postgis;
create extension pgrouting with version '2.0.1';
select pgr_version();
alter extension pgrouting update to '2.2.4';
select pgr_version();
EOF
dropdb   ___test_update
```

**Comment by cvvergara** [comment]
### Run the documentation queries

```
tools/testers/algorithm-tester.pl -documentation

```

- [ ] Done
